service: poc-serverless-typescript

plugins:
#  - serverless-offline
#  - serverless login
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  region: eu-west-1
  versionFunctions: true
  stage: blue
  environment:
    NODE_ENV: development
  apiGateway:
    restApiId: 693utogn2j
    restApiRootResourceId: hoxnr8or62

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /blue/get-all-users
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/get-tasks-by-username
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/add-user
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/add-task
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/get-single-task
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/get-single-user
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/get-all-tasks
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/update-user/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/update-task/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/delete-task/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
      - http:
          path: /blue/delete-user/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Language
              - X-Requested-With
            allowCredentials: true
          
